language: ruby

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_install:
  - docker build -t mrubyc/mrubyc-test .

script:
  - docker run --mount type=bind,src=${PWD}/,dst=/mrubyc mrubyc/mrubyc-test

